// Dates, weekday and day pillars are supplied by the calculation member.
const daySection=document.createElement('section');daySection.id='sec-days';daySection.className='day-calendar';daySection.hidden=true;
document.getElementById('controls-body').append(daySection);
const dailyMonths=chart.calendarView.years.flatMap(y=>y.months.map(m=>({...m,baziYear:y.year})));
function selectedMonth(){return monthInfo(selection.year,selection.month)}
function selectedDay(){const m=selectedMonth();return m.days.find(d=>d.date===selection.day)||m.days[0]}
function todayDate(){const c=chart.calendarView.dailyConvention,p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:c.utcOffsetSeconds===undefined?c.timezone:'UTC',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(Date.now()+(c.utcOffsetSeconds||0)*1000)).map(x=>[x.type,x.value]));return p.year.padStart(4,'0')+'-'+p.month+'-'+p.day}
function jumpToCurrent(){const date=todayDate();const m=dailyMonths.find(m=>m.startDate<=date&&date<m.endDateExclusive)|| (date<dailyMonths[0].startDate?dailyMonths[0]:dailyMonths.at(-1));selection.year=m.baziYear;selection.month=m.index;selection.day=m.days.some(d=>d.date===date)?date:m.days[0].date;syncLuck();}
function setMode(next){if(!['year','month','day'].includes(next))return;mode=next;if(mode!=='year')jumpToCurrent();renderAll();}
function chooseDay(date){const day=selectedMonth().days.find(d=>d.date===date);if(!day)return;selection.day=day.date;renderAll();}
const evaluateBeforeDays=evaluateScene;
evaluateScene=function(){if(mode!=='day')return evaluateBeforeDays();const mg=monthGz(selection.year,selection.month),dg=selectedDay().gz,month=makePillar('流月',mg[0],mg[1]),day=makePillar('流日',dg[0],dg[1]),stems=new Set([day.stem]),hidden=new Set(day.hidden);return [...baseNatal,month,day].map((p,i)=>({...p,index:i,active:p===day,stemOn:p===day||stems.has(p.stem)||hidden.has(p.stem),hiddenOn:p.hidden.map(h=>p===day||stems.has(h))}));};
const comparisonBeforeDays=renderComparison;
renderComparison=function(){comparisonBeforeDays();const next=mode==='year'?'month':mode==='month'?'day':'year',names={year:'岁运',month:'流月',day:'流日'},btn=document.getElementById('mode');btn.textContent=names[mode]+'盘';btn.setAttribute('aria-label','当前'+names[mode]+'盘，点击切换为'+names[next]+'盘');document.getElementById('progression').classList.toggle('day-focus',mode==='day');daySection.hidden=mode!=='day';if(mode==='day'){const states=evaluateScene();document.getElementById('comparison').innerHTML=[states.slice(0,4),states.slice(4,5),states.slice(5,6)].map(g=>'<div class="compare-group">'+g.map(column).join('')+'</div>').join('<div class="divider" aria-hidden="true"></div>');document.getElementById('sec-luck').hidden=true;document.getElementById('sec-years').hidden=true;document.getElementById('sec-months').hidden=false;document.getElementById('controls-body').append(document.getElementById('sec-months'),daySection);}};
function renderDays(){const m=selectedMonth(),chosen=selectedDay();selection.day=chosen.date;
 daySection.innerHTML='<div class="day-range">'+escapeText(m.startDate.replaceAll('-','.'))+' — '+escapeText(m.days.at(-1).date.replaceAll('-','.'))+'</div><div class="day-grid">'+['日','一','二','三','四','五','六'].map(x=>'<span class="weekday">'+x+'</span>').join('')+Array.from({length:m.days[0].weekday},()=>'<span aria-hidden="true"></span>').join('')+m.days.map(d=>'<button type="button" class="day-cell'+(d.date===chosen.date?' selected':'')+'" data-date="'+d.date+'" aria-pressed="'+(d.date===chosen.date)+'" aria-label="'+d.date+' '+d.gz+'"><span class="day-number">'+d.day+'</span><span class="day-gz">'+d.gz+'</span></button>').join('')+'</div>';
 daySection.querySelectorAll('.day-cell').forEach(b=>{b.onclick=()=>chooseDay(b.dataset.date);b.onkeydown=e=>{const step={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7}[e.key];if(!step)return;e.preventDefault();const i=m.days.findIndex(d=>d.date===b.dataset.date),next=m.days[i+step];if(next){chooseDay(next.date);daySection.querySelector('[data-date="'+next.date+'"]').focus()}}});
}
const renderBeforeDays=renderAll;
renderAll=function(){renderBeforeDays();const readout=document.getElementById('selected-year');readout.classList.toggle('day-date-readout',mode==='day');if(mode==='day'){renderDays();const [y,m,d]=selection.day.split('-').map(Number);readout.textContent=y+'年'+m+'月'+d+'日';}};

