'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const {readPreferences,savePreferences,resolveInput,defaultSettingsPath}=require('../../skills/cgm-bazi-chart/scripts/preferences.cjs');
const root=path.resolve(__dirname,'../..'),out=process.env.CGM_BAZI_TEST_OUTPUT||path.join(root,'output/发布修复_20261002/validation/bazi-preferences');
fs.mkdirSync(out,{recursive:true});
const sandbox=fs.mkdtempSync(path.join(out,'preferences-')),settings=path.join(sandbox,'settings.json');
const results=[],test=(name,run)=>{run();results.push({name,status:'pass'});};
const input={schema:'cgm-bazi-birth/1',name:'合成偏好测试',birth:{calendar:'solar',date:'1990-06-15',time:'12:00',sex:'male',timezone:'Asia/Shanghai',location:{name:'合成地点',longitude:120}}};
test('读取未确认设置不落盘',()=>{const s=readPreferences(settings);assert.equal(s.setupComplete,false);assert.equal(s.revision,0);assert.equal(s.conventions.smallLuck,'fixed-origin');assert.equal(fs.existsSync(settings),false);});
test('首次排盘要求用户确认',()=>assert.throws(()=>resolveInput(input,{settingsPath:settings}),e=>e.code==='SETUP_REQUIRED'));
test('保存须有确认及版本号',()=>{assert.throws(()=>savePreferences(settings,{conventions:{}}),e=>e.code==='CONFIRMATION_REQUIRED');assert.throws(()=>savePreferences(settings,{confirmed:true,conventions:{}}),e=>e.code==='REVISION_REQUIRED');assert.equal(fs.existsSync(settings),false);});
test('保存推荐并在下次读取',()=>{const s=savePreferences(settings,{confirmed:true,expectedRevision:0,conventions:{}});assert.equal(s.setupComplete,true);assert.equal(s.revision,1);assert.deepEqual(readPreferences(settings).conventions,s.conventions);});
test('缺省输入应用个人默认且不改原输入',()=>{const before=JSON.stringify(input),resolved=resolveInput(input,{settingsPath:settings});assert.equal(resolved.conventions.solarTime,'apparent');assert.equal(JSON.stringify(input),before);});
test('自动冲突返回具体字段且不改设置',()=>{
 const before=fs.readFileSync(settings,'utf8');assert.throws(()=>resolveInput({...input,conventions:{dayBoundary:'split-zi'}},{settingsPath:settings}),e=>e.code==='METHOD_CONFLICT'&&e.details.conflicts[0].key==='dayBoundary');assert.equal(fs.readFileSync(settings,'utf8'),before);
});
test('手动试算不改个人默认',()=>{const resolved=resolveInput({...input,conventions:{dayBoundary:'split-zi'}},{settingsPath:settings,manual:true});assert.equal(resolved.conventions.dayBoundary,'split-zi');assert.equal(readPreferences(settings).conventions.dayBoundary,'zi-23');});
test('旧revision不能覆盖新默认',()=>{assert.throws(()=>savePreferences(settings,{confirmed:true,expectedRevision:0,conventions:{solarTime:'civil'}}),e=>e.code==='PREFERENCES_REVISION_CONFLICT');assert.equal(readPreferences(settings).revision,1);});
test('另一个保存持锁时不覆盖',()=>{fs.writeFileSync(settings+'.lock','synthetic-lock');try{assert.throws(()=>savePreferences(settings,{confirmed:true,expectedRevision:1,conventions:{}}),e=>e.code==='PREFERENCES_REVISION_CONFLICT');}finally{fs.unlinkSync(settings+'.lock');}});
test('特殊校正输入不能保存为通用默认',()=>assert.throws(()=>savePreferences(settings,{confirmed:true,expectedRevision:1,conventions:{solarTime:'provided-apparent'}}),/solarTime/));
test('默认不能混入个人出生资料',()=>{assert.throws(()=>savePreferences(settings,{confirmed:true,expectedRevision:1,conventions:{name:'不可写入'}}),/name/);assert.equal(fs.readFileSync(settings,'utf8').includes('不可写入'),false);});
test('无效设置值明确拒绝',()=>{for(const conventions of [{dayBoundary:'other'},{smallLuck:'other'},{luckStart:'other'},{monthBoundary:'day'},{solarTime:null}])assert.throws(()=>savePreferences(settings,{confirmed:true,expectedRevision:1,conventions}));});
test('未知时辰不能自动降级太阳时',()=>assert.throws(()=>resolveInput({...input,birth:{...input.birth,time:null}},{settingsPath:settings}),e=>e.code==='TIME_REQUIRED'));
test('未知时辰不能选择时柱小运',()=>assert.throws(()=>resolveInput({...input,birth:{...input.birth,time:null},conventions:{solarTime:'civil',smallLuck:'hour-pillar'}},{settingsPath:settings,manual:true}),e=>e.code==='TIME_REQUIRED'));
test('未知时辰可明确采用固定起点日期参照',()=>{const value=resolveInput({...input,birth:{...input.birth,time:null},conventions:{solarTime:'civil'}},{settingsPath:settings,manual:true});assert.equal(value.birth.time,null);assert.equal(value.conventions.smallLuck,'fixed-origin');});
test('库与工作区共用默认路径',()=>assert.equal(defaultSettingsPath(path.join(sandbox,'library')),path.join(sandbox,'.cgm-bazi/settings.json')));
test('环境变量可统一计算与页面设置路径',()=>{const previous=process.env.CGM_BAZI_SETTINGS;try{process.env.CGM_BAZI_SETTINGS=settings;assert.equal(defaultSettingsPath(),settings);assert.equal(defaultSettingsPath(path.join(sandbox,'library')),settings);}finally{if(previous===undefined)delete process.env.CGM_BAZI_SETTINGS;else process.env.CGM_BAZI_SETTINGS=previous;}});
test('CLI返回结构化冲突且退出码2',()=>{const file=path.join(sandbox,'request.json');fs.writeFileSync(file,JSON.stringify({...input,conventions:{solarTime:'civil'}}));const result=cp.spawnSync(process.execPath,[path.join(root,'skills/cgm-bazi-chart/scripts/preferences.cjs'),'resolve','--settings',settings,'--input',file],{encoding:'utf8',windowsHide:true});assert.equal(result.status,2);assert.equal(JSON.parse(result.stdout).code,'METHOD_CONFLICT');});
test('文件损坏不静默重置',()=>{const file=path.join(sandbox,'invalid.json');fs.writeFileSync(file,'{"schema":"unknown"}');assert.throws(()=>readPreferences(file),e=>e.code==='INVALID_PREFERENCES');assert.equal(fs.readFileSync(file,'utf8'),'{"schema":"unknown"}');});
test('保存第二版个人选择并用于后续新盘',()=>{const s=savePreferences(settings,{confirmed:true,expectedRevision:1,conventions:{dayBoundary:'split-zi',smallLuck:'hour-pillar',luckStart:'three-days-year-shichen'}});assert.equal(s.revision,2);assert.equal(resolveInput(input,{settingsPath:settings}).conventions.dayBoundary,'split-zi');assert.equal(fs.existsSync(settings+'.lock'),false);});
const report={status:'executed-pass',passed:results.length,results};fs.writeFileSync(path.join(out,'preferences.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:results.length,report:path.join(out,'preferences.json')}));
