'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const {savePreferences,readPreferences}=require('../../skills/cgm-bazi-chart/scripts/preferences.cjs');
const root=path.resolve(__dirname,'../..'),out=process.env.CGM_BAZI_TEST_OUTPUT||path.join(root,'output/发布修复_20261002/validation/bazi-entry');
fs.mkdirSync(out,{recursive:true});
const sandbox=fs.mkdtempSync(path.join(out,'entry-')),settings=path.join(sandbox,'settings.json'),file=path.join(sandbox,'birth.json');
const input={schema:'cgm-bazi-birth/1',name:'合成入口测试',birth:{calendar:'solar',date:'1990-06-15',time:'23:30',sex:'male',timezone:'Asia/Shanghai',location:{name:'合成地点',longitude:120}},conventions:{solarTime:'civil',dayBoundary:'split-zi'}};
fs.writeFileSync(file,JSON.stringify(input));
const chart=path.join(root,'skills/cgm-bazi-chart/scripts/chart.cjs'),suite=path.join(root,'skills/cgm-bazi-suite/scripts/run.cjs');
const run=(script,args)=>cp.spawnSync(process.execPath,[script,...args],{encoding:'utf8',windowsHide:true});
const results=[],test=(name,fn)=>{fn();results.push({name,status:'pass'});};
test('计算CLI首次未确认不写命盘',()=>{const output=path.join(sandbox,'first.json'),r=run(chart,['birth',file,output,'--settings',settings]);assert.equal(r.status,2);assert.equal(JSON.parse(r.stderr).code,'SETUP_REQUIRED');assert.equal(fs.existsSync(output),false);});
test('套件CLI首次未确认不创建输出目录',()=>{const output=path.join(sandbox,'first-output'),r=run(suite,['birth',file,output,'--settings',settings]);assert.equal(r.status,2);assert.equal(JSON.parse(r.stderr).code,'SETUP_REQUIRED');assert.equal(fs.existsSync(output),false);});
savePreferences(settings,{confirmed:true,expectedRevision:0,conventions:{}});
test('计算CLI冲突不写命盘',()=>{const output=path.join(sandbox,'conflict.json'),r=run(chart,['birth',file,output,'--settings',settings]);assert.equal(r.status,2);const error=JSON.parse(r.stderr);assert.equal(error.code,'METHOD_CONFLICT');assert.equal(error.conflicts.length,2);assert.equal(fs.existsSync(output),false);});
test('套件CLI冲突不创建输出目录',()=>{const output=path.join(sandbox,'conflict-output'),r=run(suite,['birth',file,output,'--settings',settings]);assert.equal(r.status,2);assert.equal(JSON.parse(r.stderr).code,'METHOD_CONFLICT');assert.equal(fs.existsSync(output),false);});
test('确认的手动试算保持个人默认',()=>{const output=path.join(sandbox,'manual.json'),before=fs.readFileSync(settings,'utf8'),r=run(chart,['birth',file,output,'--settings',settings,'--manual']);assert.equal(r.status,0,r.stderr);const d=JSON.parse(fs.readFileSync(output,'utf8'));assert.equal(d.rules.conventions.dayBoundary,'split-zi');assert.equal(fs.readFileSync(settings,'utf8'),before);});
savePreferences(settings,{confirmed:true,expectedRevision:1,conventions:input.conventions});
test('手动更改默认后计算CLI自动遵循',()=>{const output=path.join(sandbox,'accepted.json'),r=run(chart,['birth',file,output,'--settings',settings]);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(fs.readFileSync(output,'utf8')).rules.conventions.dayBoundary,'split-zi');});
test('旧命盘核验不依赖现行默认',()=>{const previous=path.join(sandbox,'manual.json'),before=fs.readFileSync(previous,'utf8');savePreferences(settings,{confirmed:true,expectedRevision:2,conventions:{dayBoundary:'midnight'}});const r=run(chart,['validate',previous,'--settings',settings]);assert.equal(r.status,0,r.stderr);assert.equal(fs.readFileSync(previous,'utf8'),before);assert.equal(readPreferences(settings).conventions.dayBoundary,'midnight');});
fs.writeFileSync(path.join(out,'preferences-entry.json'),JSON.stringify({status:'executed-pass',passed:results.length,results},null,2));console.log(JSON.stringify({passed:results.length}));
