'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {render}=require('../../skills/cgm-bazi-visualization/scripts/render.cjs');
const {sha,calculateBirth}=require('../../skills/cgm-bazi-chart/scripts/chart.cjs');
const root=path.resolve(__dirname,'../..'),base=path.join(root,'skills/cgm-bazi-visualization/assets/template/book.html');
const manifest=path.join(root,'skills/cgm-bazi-visualization/assets/kimi-book-v1.json');
const out=process.env.CGM_BAZI_TEST_OUTPUT||path.join(root,'output/发布修复_20261002/validation/render-regression');fs.mkdirSync(out,{recursive:true});
const d=calculateBirth({schema:'cgm-bazi-birth/1',name:'</script><script>alert(1)</script>',birth:{calendar:'solar',date:'1990-06-15',time:'12:00',sex:'male',timezone:'Etc/UTC',location:{name:'<img src=x onerror=alert(1)>',longitude:0,latitude:0}},initial:{year:2026,month:0}});
const target=path.join(out,'portable.html'),report=render(d,manifest,target);
const html=fs.readFileSync(target,'utf8'),scripts=[...html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)];
assert.equal(sha(JSON.stringify(JSON.parse(scripts.find(m=>m[1].includes('chart-data'))[2]))),sha(JSON.stringify(d)),'Embedded facts must match JSON serialization');
for(const m of scripts.filter(m=>!m[1].includes('application/json')))new vm.Script(m[2]);
assert(!html.includes('<script>alert(1)</script>'));assert(!html.includes('<img src=x'));
assert([...html.matchAll(/url\('([^']+)'\)/g)].every(m=>m[1].startsWith('data:')),'Standalone CSS must embed every resource');
assert(report.resources.length===2&&report.resources.every(r=>r.path.endsWith('.ttf')),'The public template must only require its two font files');
const exportAssets=JSON.parse(scripts.find(m=>m[1].includes('export-assets'))[2]);assert.equal(exportAssets.fonts.length,2);assert.equal(Object.hasOwn(exportAssets,'paper'),false);
assert(!html.includes('data:image/png;base64,'),'No background texture may remain embedded in the public page');
assert(html.includes('--paper:#FFF9EE;'),'The existing warm background remains');
assert.equal(sha(fs.readFileSync(base)),JSON.parse(fs.readFileSync(manifest,'utf8')).sourceSha256);
assert(!fs.readFileSync(target+'.provenance.json','utf8').includes('Users\\\\'));
const relocated=path.join(out,'moved');fs.mkdirSync(relocated,{recursive:true});fs.copyFileSync(target,path.join(relocated,'chart.html'));
assert.equal(fs.readFileSync(path.join(relocated,'chart.html'),'utf8'),html);
console.log('PASS: synthetic facts, script safety, portable fonts, warm background without texture, template hash, executable script syntax');
